### ISSUE TITLE
Does not build any more?

### ISSUE THREAD

**Issue by georgbachmann** [home-assistant/HAKit#51]
Just wanted to ask if this package is still maintained? Wanted to try it out to build a native dashboard (as I suck at CSS) but I can't get it to compile any more...

**Comment by bgoncal** [comment]
Can you provide more details? What fails? Which Xcode version?

**Comment by georgbachmann** [comment]
I simply added the SPM and hit compile. That was on the latest Xcode version... haven't tried with the one that just dropped today...

**Comment by bgoncal** [comment]
Without details it's not possible to help you out, if you try to compile again please take a screenshot of the error and copy and paste any error messages

**Comment by georgbachmann** [comment]
I attached some screenshots of the problem.
What I did:
- Create a new Xcode Project
- Go to the Swift Package Manager and add this repo
- Hit compile
- This will cause the compile errors

<img width="605" alt="Bildschirmfoto 2024-03-06 um 19 21 13" src="https://github.com/home-assistant/HAKit/assets/893113/7663e0c5-5bcf-4b35-971f-40585ced5bd5">

**Comment by Nerkyator** [comment]
Same here with latest release (0.4)

**Comment by bgoncal** [comment]
Sorry I forgot to check, I'm setting a reminder for this week, I'll get back to you.

**Comment by Nerkyator** [comment]
I think problem is related to this function
`func didReceive(event: Starscream.WebSocketEvent, client: Starscream.WebSocket) `
that should be implemented as
`func didReceive(event: WebSocketEvent, client: WebSocketClient)`

hope this can help you!

**Comment by bgoncal** [comment]
Oh, this does ring a bell, we are currently evaluating which version for StarScream to use, I'll get back with updates.

**Comment by bgoncal** [comment]
I just checked, there was an issue indeed, I am currently preparing a release 0.4.1, I tested importing using it and it seems to work properly now, I'll let you know when it is released, meanwhile if you want to move forward while it is in pre-release you can use the commit id: b99c77e5e73b1a92661fa09b299c42a51d82d18d

<img width="1300" alt="Screenshot 2024-04-03 at 11 31 51" src="https://github.com/home-assistant/HAKit/assets/5808343/96d63a63-b3e9-4b1a-bc6f-af90fa63ca6d">

**Comment by Nerkyator** [comment]
Hi @bgoncal, I just tried the commit you linked me to above, and it seems to be working. I'm building a dashboard in SwiftUI, so I'm making heavy use of HAKit. After using it for a few hours, I haven't noticed any problems. Good work! 🥳

**Comment by bgoncal** [comment]
> Hi @bgoncal, I just tried the commit you linked me to above, and it seems to be working. I'm building a dashboard in SwiftUI, so I'm making heavy use of HAKit. After using it for a few hours, I haven't noticed any problems. Good work! 🥳

Nice! Im glad to hear that, btw if you build something cool, consider contributing to the HA iOS App, I will be happy to assist you when the time comes :)

**Comment by georgbachmann** [comment]
Hey @Nerkyator ... I'd also love to build myself a SwiftUI dashboard... that's why I was searching and finding this repo here in the first place. Would also love to see your result as an inspiration... any maybe we can even colab? :)
@bgoncal thank you so much for your support here!

**Comment by Nerkyator** [comment]
hey @georgbachmann, I already have a (really early stage) working prototype based on a my lib written on top of HAKit (it was broken until _bgoncal_ merged some PR so I forked it removing starscream and implementing native websocket communication just to make it work, but now I think I can switch back to main HAKit). I can send you some screenshot (but beware, I suck at UI)

**Comment by georgbachmann** [comment]
@Nerkyator oh yeah... would be super nice... is your plan to keep it private? Cause if you want we could both work on it? (no pressure)
I am also not super good on UI... I love building nice UI, I think I notice then it's not beautiful, but I am not a designer :)

I just would love to have a cool native experience... I like the regular HA app, but it's just not as cool as it could be. I also plan to one day have a tablet up the wall and i like it to be a cool and fun native experience...

My plan would be... just in my head now... to build all kinds of various controls/charts/... and then have some way (not sure yet... yaml?!?) of configuring the a dashboard... have some layout options and so on... just a vague idea in my head at that time...

But hey... if you want do split efforts... I'd be happy :) I am iOS developer since iOS3... so quite some experience :)
But again... no pressure :)

**Comment by Nerkyator** [comment]
@georgbachmann (and @bgoncal), I'd like to share three "demos" of my current work based on HAKit. I've developed a library (called Veb) on top of HAKit to abstract entities (this is a work in progress). With this approach, on the app side, you simply need to create an instance of Veb, pass it to an instance of a Light (for example), and you're all set.

For example:
```

let veb = Veb(address: HA_ADDRESS, token: HA_TOKEN, listenedEntities: Configuration.listenedEntities)
var kitchen_light = Light(veb: veb, entityId: "light.kitchen")
```
From this point onwards:

`kitchen_light.state` is a published value representing the light's state.
`kitchen_light.toggle(), kitchen_light.turnOn(), and kitchen_light.turnOff()` are methods to control the light.
I've attached the demos here.

Repo is currently private due to work-in-progress in my spare time :)
PS: Right now there is no runtime configuration to create controls at runtime. Project is a private dashboard to put on a wall for my HA installation so there is no need to have this feature right now, but I'm pretty sure that a way to configure it can be found.
PS2: localization is in italian, sorry :P

**Living room - early stage**
![Living room - early stage](https://github.com/home-assistant/HAKit/assets/4661466/1b3d2045-2def-4c35-b73e-465088abd8f2)

**Energy consumptions - Work in progress**
![Energy consumptions - Work in progress](https://github.com/home-assistant/HAKit/assets/4661466/70c3a08a-d951-4a91-9998-c3b17ed0218e)

**Home page - almost done**
![Home page - almost done](https://github.com/home-assistant/HAKit/assets/4661466/6ec85f08-eace-4aac-bd48-42b54c8e70c2)

**Comment by georgbachmann** [comment]
That already looks quite amazing! Nice!!!

**Comment by Nerkyator** [comment]
@bgoncal do you think a release can be made with current fixes?

**Comment by Nerkyator** [comment]
> > @bgoncal do you think a release can be made with current fixes?
> 
> I moved 0.4.1 from pre-release to release, can you check if it works for you and get back to me?

Just tried with

```
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(
            url: "https://github.com/home-assistant/HAKit", 
            exact: "0.4.1"
        ),
        
    ]
```
but there are problems on HAKit dependencies (StarScream). 
This is the XCode error message

`Failed to resolve dependencies Dependencies could not be resolved because package 'hakit' is required using a stable-version but 'hakit' depends on an unstable-version package 'starscream' and root depends on 'hakit' 0.4.1.`

**Comment by bgoncal** [comment]
Funny thing is that if you point to branch "main" this issue doesn't happens... I am reading this thread now https://github.com/realm/SwiftLint/issues/4558

I'll let you know when I have new info

**Comment by Nerkyator** [comment]
It's working! (and strangely without deleting derived data, caches and changing home)...thanks!
